# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Admin
  admin_email: admin@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 31dbce3b8ec6d64ee0d3d925803a0d76c55e5bbc44039a7ccf9ebb362d1b9ce13fbd931f4aa52e360769d27fb6dba3553e74776f628e73defac58db959f947b3

test:
  domain_name: example.com 
  secret_key_base: 415292d354e23d4290dcc121d88da853a3ab47f070fb6f0275f853921ebc61c26931c79cc56d99058a81ffb24c2c892ba0d837d5c7ada5b93446ea643c9f5696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["NABITO_ADMIN_NAME"] %>
  admin_email: <%= ENV["NABITO_ADMIN_EMAIL"] %>
  admin_password: <%= ENV["NABITO_ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["NABITO_DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["NABITO_SECRET_KEY_BASE"] %>
